### ISSUE TITLE
How to build for development?

### ISSUE THREAD

**Issue by marty1885** [usefulsensors/useful-transformers#13]
I'm interested the project. But I don't get how to install the repo for development. I tried `pip install -e .` to install from repo. But running the provided sample shows it can't find pybind_whisper.

```bash
❯ cp /path/to/rknpu2/.../librknnrt.so example/whisper/
❯ python -m useful_transformers.transcribe_wav
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/marty/Documents/useful-transformers/examples/whisper/transcribe_wav.py", line 4, in <module>
    from .whisper import decode_wav_file
  File "/home/marty/Documents/useful-transformers/examples/whisper/whisper.py", line 13, in <module>
    from .pybind_whisper import WhisperModel as CWhisperModel
ModuleNotFoundError: No module named 'useful_transformers.pybind_whisper'
```

How can I run in a development setting?

**Comment by RoboMagus** [comment]
I'm expecting that the setup would've shown errors indicating a pybind issue.
What worked for me is to install the unlisted dependencies prior to the dev instalation:

```
pip install pybind11[global] torch
pip install -e .
```

**Comment by keveman** [comment]
@marty1885 The following sequence of commands worked well for me:

```
$ python -m venv le_us
$ source le_us/
$ source le_us/bin/activate
$ cd useful-transformers/
$ python -m pip install .
$ taskset -c 4-7 python -m useful_transformers.transcribe_wav
```

This is what I do for local development myself.
If installing the whl file (as specified in README.md) worked for you, then you can build the whl file and install it explicitly as follows:

```
$ python -m pip wheel .
$ python -m pip install useful_transformers-0.1-cp310-cp310-linux_aarch64.whl
```

(Note, your exact python version determines the name of the .whl file, so use the one that gets built on your machine.)

**Comment by marty1885** [comment]
Thanks for the help. Figured out the issues.

1. Must build with Python 3.10. Pybind hasn't support Python 3.11 yet.
2. Must install with `python -m pip install .`

So the following commands work for me using micromamba (should with conda too).

```bash
micromamba create -n useful
micromamba activate useful
cd /path/to/useful-transofrmers
python -m pip install .
taskset -c 4-7 python -m useful_transformers.transcribe_wav
```

**Comment by ibash** [comment]
Mostly a note to self... when building a fresh install with [uv](https://github.com/astral-sh/uv):

```bash
# cloning the fork with this fix: https://github.com/usefulsensors/useful-transformers/pull/43
git clone https://github.com/BluewhaleRobot/useful-transformers.git

uv python install 3.10
uv venv --python $(uv python find 3.10)

source .venv/bin/activate
uv pip install pybind11[global]
uv pip install .
taskset -c 4-7 python3 -m useful_transformers.transcribe_wav
```
