### ISSUE TITLE
Is it possible to set input language with whisper-base.tflite?

### ISSUE THREAD

**Issue by SchweitzerGAO** [usefulsensors/useful-transformers#32]
Here's the thing, I speak Chinese but the result is in English with similar meaning. So I am wondering if it is possible to set the input language so that the output will be in the same language as the input.

**Comment by SchweitzerGAO** [comment]
Switch to onnx with a seperated encoder and decoder model will do.

**Comment by Ctrl-cv-engineer** [comment]
> Switch to onnx with a seperated encoder and decoder model will do.切换到具有分离编码器和解码器模型的 onnx 即可。

Could you please explain in detail how you solved this problem? Thank you very much
